import Head from "next/head";
import Image from "next/image";
import MainLayoute from "../layoutes/mainLayoute/MainLayoute";
import styles from "../styles/Home.module.css";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import DashBoardAdminHome from "../component/dashboardAdminHome/dashBoardAdminHome";
import { FaMemory } from "react-icons/fa";
import { useDispatch } from "react-redux";
import Timer from "../component/timer/Timer";
import "react-toastify/dist/ReactToastify.css";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Time Tracking Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ToastContainer />
      {/* <MainLayoute /> */}
      <Timer />

      <DashBoardAdminHome />
    </div>
  );
}
